### ISSUE TITLE
Merge historic and scheduled talks

### ISSUE THREAD

**Issue by fkemmer** [hfuunfug/unfug.org#23]
Existing separation of historic talks ("Historie") and scheduled talks ("Terminplan" on existing page) is not really required. Merging the contents (and menu items) into a generic entry called "talks" should suffice.
Upcoming talks on top and history events down below.

**Comment by matthiasbeyer** [comment]
I will fix this in my PR #12

**Comment by matthiasbeyer** [comment]
done.
